### ISSUE TITLE
Tell newcomers how to get slc

### ISSUE THREAD

**Issue by francispotter** [strongloop/loopback-example-app#59]
People new to loopback may end up here first and decide to run the sample application before learning more (as I did just now). You may want to add something to the README saying e.g. "if this is your first time using the loopback framework then run sudo npm install -g strongloop to get the slc command."

**Comment by OwenBrotherwood** [comment]
@crandmck 
This issue seems to be solved. 
Should I go through it as a beginner to double check?

**Comment by crandmck** [comment]
I made a few clarifications in the README.  In general, everything will work better if one just installs the whole StrongLoop package, rather than installing the generator, so I changed that.  

I think we can close this. If you have further specific points, please open new issues for them.  Thanks!

**Comment by OwenBrotherwood** [comment]
@crandmck 
https://github.com/strongloop/loopback-getting-started-intermediate
- spot on :)
