### ISSUE TITLE
geoPoint api nearby not showing up

### ISSUE THREAD

**Issue by Karabi-Choudhury** [strongloop/loopback-example-app#70]
I was trying to build a similar application.I have added the same rest connector "geo" as in application.I have a model city with one property geo as geoPoint. 
Now when i view in explorer i can't see the nearby api for city.Even tried calling the api,but that doesnot works.
wonder what am i missing?

**Comment by Karabi-Choudhury** [comment]
Any update?

**Comment by crandmck** [comment]
@Karabi-Choudhury Please post questions of this nature to the LoopBack Google Group forum: https://groups.google.com/forum/#!forum/loopbackjs.

I'm closing this, since the issues in this repo are specifically for problems or requests related to this example application.  Also, as you may have noticed, we don't monitor the issues in this particular repo very closely.  Your best bet to get your question answered is to ask in the forum.
